### PR TITLE
Fix StillPicture for radio plugin

### LINKED ISSUE #151: radio plugin is not working
See https://www.vdr-portal.de/forum/thread/136098-softhddevice-drm-gles-raspberry-4-und-5/?postID=1387429#post1387434

I would not introduce a hack to handle direct ES without any pes header. This has to be solved in the plugin itself.
But number 2) is something, we have to look in. 

[This](https://github.com/vdr-projects/vdr-plugin-radio/blob/master/radioimage.c#L59) is, what happens on the radio-plugin side here. And the *.mpg files start with 0x00 0x00 0x01 0xB3, so i guess this is the ES part...

### PR DESCRIPTION
**Pull request by rellla**
I just pushed this one to better comment and fix the remaining issues.

### CODE REVIEW

**Comment by rellla** [comment]
Problem description:

The radio plugin invokes a cDevice::StillPicture combined with PlayAudio (and no video stream). Currently this can't be handled.
Next, cDevice::StillPicture can arrive in BUFFERING, STOP or PLAY state and has to be handled correctly - even if the BUFFERING state was triggered by a PlayEvent(). An new PlayEvent() won't arrive in this case.
We have to take care, that the deinterlacer/filter settings are right, that we don't sync in the renderer and that we don't trigger a video buffer underrun. 
If the PES from StillPicture has a pts value it can't be used to synchronize with audio at all, because it is a fake one.
If it has no pts value (which is valid imho), the plugin can't handle it atm.

**Comment by fwolter** [comment]
If StillPicture can be called in nearly every state, and the state the machine is currently in shall immediately continue after StillPicture has been called, the STILL_PICTURE state should be removed. Because it is not a state, then, but only an event, which need to be handled.

**Comment by rellla** [comment]
That would be the right approach. I will try it that way.

**Comment by rellla** [comment]
Together with https://github.com/rellla/vdr-plugin-radio/tree/fix-stillpicture it was tested on RK3399 without any issues so far.
Doing PlayPes in audio only streams does not work, though. This is, what i would expect, because we can't sync with faked video pts. I also wouldn't do any hack around that.
Doing StillPicture without video pts also doesn't work and probably could be implemented as a follow-up, because we don't sync in Stillpicture anyway.
External StillPicture invocation with a "valid" fake pts does work as long as the dvbplayer only sends audio data - and this is what we want here.

File: softhddevice.cpp [hunk 1]
```diff
@@ -1183,6 +1157,8 @@ int cSoftHdDevice::PlayVideo(const uchar *data, int size)
 int cSoftHdDevice::PlayPipVideo(const uchar *data, int size)
 {
 //	LOGDEBUG("device: %s: %p %d", __FUNCTION__, data, size);
+	m_receivedVideo = true;
```
Comment (fwolter) [inline softhddevice.cpp]: I think the PIP shouldn't set this, because this flag is only needed for buffering/synced start. Could lead to false positives, or?

File: softhddevice.cpp [hunk 2]
```diff
@@ -866,7 +833,11 @@ void cSoftHdDevice::StillPicture(const uchar *data, int size)
  */
 void cSoftHdDevice::HandleStillPicture(const uchar *data, int size)
 {
-	SetState(STILL_PICTURE);
+	m_pRender->SetPlaybackPaused(false);
+	m_pVideoStream->SetDeinterlacerDeactivated(true);
```
Comment (fwolter) [inline softhddevice.cpp:839]: Is this disabled again after still picture is over?

Comment (rellla) [reply softhddevice.cpp:839]: It is disabled as soon as a new PlayEvent with !audio_only arrives or when the filter thread was cancelled, e.g. in  DeviceClear(). Disabling it on leaving HandleStillPicture is too early. Because of the different threads this could lead to activating the deinterlacer as soon the frame arrives at the filter init.
So I decided that the best place would be entering PLAY...

File: softhddevice.cpp (hunk 1 above)
Comment (rellla) [reply softhddevice.cpp]: Yes, i think you are right.

File: softhddevice.cpp (hunk 2 above)
Comment (fwolter) [reply softhddevice.cpp:839]: The triggering of DeviceClear() when StillPicture() is invoked was the missing piece of the puzzle.

Comment (rellla) [reply softhddevice.cpp:839]: I don't understand exactly what you mean :) Is it ok for you as is?

Comment (fwolter) [reply softhddevice.cpp:839]: Yes, it was the missing puzzle piece for *me* :)

**Comment by fwolter** [comment]
The state machine graph needs to be updated.

**Comment by rellla** [comment]
> The state machine graph needs to be updated.

Ah,  yes. Forgot that.

**Comment by rellla** [comment]
There were some things missing in the state machine graph before already. I would suggest to drop all Events, that don't do state changes for better readability. WDYT?

**Comment by fwolter** [comment]
OK

**Comment by rellla** [comment]
And maybe also drop the DetachEvents? They can be triggered in any state?

**Comment by fwolter** [comment]
Sounds reasonable. Go ahead!
