### PR TITLE
lock audiodecoder

### LINKED ISSUE #232: audio decoder is not threadsafe
I think it is, but there seems to be a problem though. I had a segfault in Decode()->ffmpeg when doing FlushBuffers()....
Maybe we need to lock the audio decoder. Needs some investigation....

### PR DESCRIPTION
**Pull request by rellla**

### CODE REVIEW

File: codec_video.cpp [hunk 1]
```diff
@@ -221,17 +218,14 @@ int cVideoDecoder::Open(enum AVCodecID codecId, AVCodecParameters * par,
...
 		}
 		m_pVideoCtx->hw_device_ctx = hwDeviceCtx;
 		m_pVideoCtx->pix_fmt = AV_PIX_FMT_DRM_PRIME;
 	}
 
-	if (par) {
-		if ((avcodec_parameters_to_context(m_pVideoCtx, par)) < 0)
-			LOGERROR("videocodec: %s: %s: insert parameters to context failed!", m_identifier, __FUNCTION__);
-	}
+	if (par && (avcodec_parameters_to_context(m_pVideoCtx, par) < 0))
```
Comment (fwolter) [inline codec_video.cpp:227]:
```suggestion
	if (par && avcodec_parameters_to_context(m_pVideoCtx, par) < 0)
```

File: codec_video.cpp [hunk 2]
```diff
@@ -258,10 +252,8 @@ int cVideoDecoder::Open(enum AVCodecID codecId, AVCodecParameters * par,
 		}
 	}
 
-	if (codec->capabilities & AV_CODEC_CAP_FRAME_THREADS ||
-		AV_CODEC_CAP_SLICE_THREADS) {
+	if (codec->capabilities & AV_CODEC_CAP_FRAME_THREADS || AV_CODEC_CAP_SLICE_THREADS)
```
Comment (fwolter) [inline codec_video.cpp:255]: Although you didn't change it in this commit, but there need to be parentheses around the binary operation.
```suggestion
	if ((codec->capabilities & AV_CODEC_CAP_FRAME_THREADS) || AV_CODEC_CAP_SLICE_THREADS)
```

**Comment by rellla** [comment]
Thanks, will change that.
