### PR TITLE
Fix uninitilized access

### LINKED ISSUE #58: Access to uninitilized values during playback
I'll have a look into it.
```
==152216== Thread 13 dvbplayer:
==152216== Conditional jump or move depends on uninitialised value(s)
==152216==    at 0x5CB3230: cSoftHdAudio::CheckForFilterReady(AVCodecContext*) (audio.cpp:774)
==152216==    by 0x5CB3387: cSoftHdAudio::Filter(AVFrame*, AVCodecContext*) (audio.cpp:813)
==152216==    by 0x5CB9437: cAudioDecoder::Decode(AVPacket const*) (codec_audio.cpp:413)
==152216==    by 0x5CCEDAF: cSoftHdDevice::PlayAudio(unsigned char const*, int, unsigned char) (softhddevice.cpp:1243)
==152216==    by 0x2025AB: cDevice::PlayTsAudio(unsigned char const*, int) (device.c:1624)
==152216==    by 0x202A2F: cDevice::PlayTs(unsigned char const*, int, bool) (device.c:1685)
==152216==    by 0x21A7FF: cPlayer::PlayTs(unsigned char const*, int, bool) (player.h:48)
==152216==    by 0x218867: cDvbPlayer::Action() (dvbplayer.c:663)
==152216==    by 0x2DE67B: cThread::StartThread(cThread*) (thread.c:294)
==152216==    by 0x4F4202F: start_thread (pthread_create.c:442)
==152216==    by 0x4FABF5B: thread_start (clone.S:79)
==152216==
==152216== Conditional jump or move depends on uninitialised value(s)
==152216==    at 0x5CB32A0: cSoftHdAudio::CheckForFilterReady(AVCodecContext*) (audio.cpp:786)
==152216==    by 0x5CB3387: cSoftHdAudio::Filter(AVFrame*, AVCodecContext*) (audio.cpp:813)
==152216==    by 0x5CB9437: cAudioDecoder::Decode(AVPacket const*) (codec_audio.cpp:413)
==152216==    by 0x5CCEDAF: cSoftHdDevice::PlayAudio(unsigned char const*, int, unsigned char) (softhddevice.cpp:1243)
==152216==    by 0x2025AB: cDevice::PlayTsAudio(unsigned char const*, int) (device.c:1624)
==152216==    by 0x202A2F: cDevice::PlayTs(unsigned char const*, int, bool) (device.c:1685)
==152216==    by 0x21A7FF: cPlayer::PlayTs(unsigned char const*, int, bool) (player.h:48)
==152216==    by 0x218867: cDvbPlayer::Action() (dvbplayer.c:663)
==152216==    by 0x2DE67B: cThread::StartThread(cThread*) (thread.c:294)
==152216==    by 0x4F4202F: start_thread (pthread_create.c:442)
==152216==    by 0x4FABF5B: thread_start (clone.S:79)
==152216==
==152216== Thread 31 filter:
==152216== Conditional jump or move depends on uninitialised value(s)
==152216==    at 0x5CDBC10: cVideoRender::EnqueueFB(AVFrame*) (videorender.cpp:1224)
==152216==    by 0x5CD789F: cFilterThread::Action() (threads.cpp:441)
==152216==    by 0x2DE67B: cThread::StartThread(cThread*) (thread.c:294)
==152216==    by 0x4F4202F: start_thread (pthread_create.c:442)
==152216==    by 0x4FABF5B: thread_start (clone.S:79)
==152216==
==152216== Thread 2 display:
==152216== Conditional jump or move depends on uninitialised value(s)
==152216==    at 0x4F16C80: __vfprintf_internal (vfprintf-process-arg.c:58)
==152216==    by 0x4F36D4F: __vsnprintf_internal (vsnprintf.c:114)
==152216==    by 0x4FA7347: __vsyslog_internal (syslog.c:218)
==152216==    by 0x4FA788F: vsyslog (syslog.c:100)
==152216==    by 0x5CC42F3: cSoftHdLogger::LogDebug2(int, char const*, ...) (logger.cpp:212)
==152216==    by 0x5CD9BF3: cVideoRender::HandleDropDup(long, long) (videorender.cpp:515)
==152216==    by 0x5CD9EA7: cVideoRender::Sync(AVFrame*) (videorender.cpp:569)
==152216==    by 0x5CDAEE7: cVideoRender::DisplayFrame() (videorender.cpp:979)
==152216==    by 0x5CD6543: cDisplayThread::Action() (threads.cpp:95)
==152216==    by 0x2DE67B: cThread::StartThread(cThread*) (thread.c:294)
==152216==    by 0x4F4202F: start_thread (pthread_create.c:442)
==152216==    by 0x4FABF5B: thread_start (clone.S:79)
==152216== Thread 6 decoding:
==152216== Conditional jump or move depends on uninitialised value(s)
==152216==    at 0x5CD6DFC: cFilterThread::Init(AVCodecContext const*, AVFrame*, int) (threads.cpp:254)
==152216==    by 0x5CDC4A7: cVideoRender::RenderFrame(AVCodecContext*, AVFrame*) (videorender.cpp:1365)
==152216==    by 0x5CDF5DB: cVideoStream::DecodeInput() (videostream.cpp:277)
==152216==    by 0x5CD62F7: cDecodingThread::Action() (threads.cpp:60)
==152216==    by 0x2DE67B: cThread::StartThread(cThread*) (thread.c:294)
==152216==    by 0x4F4202F: start_thread (pthread_create.c:442)
==152216==    by 0x4FABF5B: thread_start (clone.S:79)
```

### PR DESCRIPTION
**Pull request by fwolter**
This fixes the Valgrind errors for this class reported in #58. It initializes all members with their default values. I find this solution quite appealing. It could be applied to all classes so we can eliminate these errors once and for all. WDYT?

Fixes https://github.com/rellla/vdr-plugin-softhddevice-drm-gles/issues/58

### CODE REVIEW

**Comment by rellla** [comment]
I'm not aware with that kind of default initializing. In general, we could do that. But where are the default values in the example above?
Can we combine ": default" with more complex things except initialization in the constructor?

**Comment by fwolter** [comment]
Basically primitives like int or bool are initilized with 0/false by the `= default` constructor. And more complex things can be done like in line 79-81.

I just saw m_trickForward needs to be initilized with true manually.

**Comment by rellla** [comment]
Ok. I think m_trickForward could be false, too. Need to track it down. It should mostly be coupled with m_trickspeed.

**Comment by fwolter** [comment]
I need to correct myself. `= default` does not zero-initilize the primitives.

drmPrimeHandleToFD() does not specify to set errno: https://gitlab.freedesktop.org/mesa/libdrm/-/blob/main/xf86drm.h#L834

File: videorender.cpp [hunk 1]
```diff
@@ -1297,7 +1240,7 @@ void cVideoRender::EnqueueFB(AVFrame *inframe)
 
 			int primefd;
 			if (drmPrimeHandleToFD(fdDrm, buf->Handle(0), DRM_CLOEXEC | DRM_RDWR, &primefd))
-				LOGERROR("videorender: %s: Failed to retrieve the Prime FD (%d): %m", __FUNCTION__, errno);
+				LOGERROR("videorender: %s: Failed to retrieve the Prime FD", __FUNCTION__);
 			buf->SetFdPrime(0, primefd);
```
Comment (rellla) [inline videorender.cpp:1244]: Sure? Imho drmPrimeHandleToFD returns the return value of ioctl (0 on success, -1 on error) and ioctl sets errno in case of error?!

File: videorender.h [hunk 2]
```diff
@@ -234,7 +231,7 @@ class cVideoRender
 	cDrmBuffer *m_pBufOsd;              ///< pointer to osd drm buffer object
 	cDrmBuffer m_bufBlack;              ///< black drm buffer object
 	struct lastFrame *m_pLastFrame;     ///< pointer to last rendered frame struct (for later free)
-	int m_numBuffers;                   ///< numer of framebuffers currently set up
+	int m_numBuffers = 0;               ///< numer of framebuffers currently set up
```
Comment (rellla) [inline videorender.h]: You could fix the numBer typo on-the-fly ;)

File: videorender.cpp (hunk 1 above)
Comment (fwolter) [reply videorender.cpp:1244]: No, not sure, I just didn't see the fact in the doc. It calls drmIoctl(): https://gitlab.freedesktop.org/mesa/libdrm/-/blob/main/xf86drm.c#L3367 So, it probably sets errno. I revert it.
