### PR TITLE
fix stillpicture

### LINKED ISSUE #116: deadlock with stillpicture
https://gist.github.com/rellla/67a2f8f7c328e23d2bef4a17966df967

Just for the record, needs more investigation

pause after jump on marks is set

### PR DESCRIPTION
**Pull request by rellla**
we introduced a deadlock...

### CODE REVIEW

File: softhddevice.cpp [hunk 1]
```diff
@@ -1027,13 +1027,26 @@ void cSoftHdDevice::SetVolumeDevice(int volume)
  *
  * @param data    A complete PES packet with optionally fragmented payload
  * @param size    the length of the PES packet including header
+ *
+ * This function must not be called within OnEventReceived, otherwise we get a deadlock,
  */
 int cSoftHdDevice::PlayVideo(const uchar *data, int size)
 {
 	// LOGDEBUG("device: %s: %p %d", __FUNCTION__, data, size);
 	if (IsDetached())
```
Comment (fwolter) [inline softhddevice.cpp]: In which case is Play*() called in detached mode? Do we need this if at all?

Comment (rellla) [reply softhddevice.cpp]: > In which case is Play*() called in detached mode? Do we need this if at all?

Never. We should not need it. If we need it, it should be a bug at caller side. VDR itself doesn't do Play* in detached mode. A quick test with a DETA during normal live tv and replay confirms that.
It should be safe to simply remove the IsDetached() test in PlayVideo/PlayAudio.

Comment (fwolter) [reply softhddevice.cpp]: I like removing unnecessary code!
