### PR TITLE
drm: don't display pip if video is scaled

### LINKED ISSUE #147: Scaling pip video is broken
It seems, there is some error in the scaling calculation algorithm. The atomic commits reports values out of range. At least crtc_y is wrong. crtc_x probably too.

### PR DESCRIPTION
**Pull request by rellla**
If the main video is scaled within a menu, the pip video is very small. RK3399 has some minimum drm plane size to be set - a width of 160 pixels was found out by testing. Because the pip video is very small and a "normal" user can't multi-task with 2 videos and a menu, we disable it for simplicity.

The minimum scale factor is hardcoded to 10% in the setup menu. So on a display which has a width > 1600px there should be no problem with having the pip area too small.

### CODE REVIEW

File: videorender.cpp [hunk 1]
```diff
@@ -412,11 +418,11 @@ int cVideoRender::CommitBuffer(cDrmBuffer *buf, cDrmBuffer *pip)
 
 	// handle the pip plane
 	if (pipPlane->GetId()) {
-		if (IsPipActive() && pip) {
+		if (IsPipActive() && pip && !m_videoIsScaled) {
 			SetPipBuffer(pip);
 			pipPlane->SetPlane(modeReq);
 			modeSet |= MODESET_PIP;
-		} else if (IsPipActive() && m_pCurrentlyPipDisplayed) {
+		} else if (IsPipActive() && m_pCurrentlyPipDisplayed  && !m_videoIsScaled) {
```
Comment (fwolter) [inline videorender.cpp]: You could check if the PIP should be displayed in a more centralized way. Then, this function can be re-used. For example extend IsPipActive() by m_pCurrentlyPipDisplayed and m_videoIsScaled. Maybe the null checks can also be removed, then. Good practice is to know *beforehand* if something is null, so you don't need a null check at all.

**Comment by rellla** [comment]
What about this solution?

File: videorender.cpp [hunk 2]
```diff
@@ -402,34 +411,22 @@ int cVideoRender::CommitBuffer(cDrmBuffer *buf, cDrmBuffer *pip)
...
-		} else if (IsPipActive() && m_pCurrentlyPipDisplayed  && !m_videoIsScaled) {
-			SetPipBuffer(m_pCurrentlyPipDisplayed);
-			pipPlane->SetPlane(modeReq);
-			modeSet |= MODESET_PIP;
-		} else {
+		else
 			pipPlane->ClearPlane(modeReq);
-			modeSet |= MODESET_PIP;
-		}
+		modeSet |= MODESET_PIP;
```
Comment (fwolter) [inline videorender.cpp:430]: Is this advertently outside the else? Then, there should be an empty line, when omitting the curly braces.

**Review by fwolter — CHANGES_REQUESTED** [review]
Otherwise, LGTM.
