### PR TITLE
detect stream discontinuity

### LINKED ISSUE #199: sync issue when skipping cutted areas
To reproduce:
Enable "SkipEdited = 1" and "PauseOnMarkJump = 0" so that cutted areas are skipped automatically during replay without stopping at the marks.

The replay gets out of sync like the following:

```
Feb 18 08:41:58 rpi4 vdr[22520]: [23633] skipping from 27524 (0:18:20.24) to 41910 (0:27:56.10)
Feb 18 08:42:10 rpi4 vdr[22520]: [23633] [softhddevice] pes: TruncateBufferUntilFirstValidData: truncated 648 of 1114 bytes while searching for sync word
Feb 18 08:42:10 rpi4 vdr[22520]: [22534] [softhddevice][AV_Sync] Frame dropped (drop 14, dup 0) Pkts 192 Frames 2 UsedBytes 1401728 audio 19:12:30.391 video 19:02:54.855 Delay 0ms diff -575536ms
Feb 18 08:42:10 rpi4 vdr[22520]: [22534] [softhddevice][AV_Sync] Frame dropped (drop 15, dup 0) Pkts 192 Frames 2 UsedBytes 1406144 audio 19:12:30.411 video 19:02:54.895 Delay 0ms diff -575516ms
Feb 18 08:42:10 rpi4 vdr[22520]: [22534] [softhddevice][AV_Sync] Frame dropped (drop 16, dup 0) Pkts 192 Frames 2 UsedBytes 1410752 audio 19:12:30.430 video 19:02:54.935 Delay 0ms diff -575495ms

...... repating .......

Feb 18 08:42:14 rpi4 vdr[22520]: [22534] [softhddevice][AV_Sync] Frame dropped (drop 210, dup 0) Pkts 113 Frames 2 UsedBytes 1486784 audio 19:12:34.311 video 19:03:02.695 Delay 0ms diff -571616ms
Feb 18 08:42:14 rpi4 vdr[22520]: [22534] [softhddevice][AV_Sync] Frame dropped (drop 211, dup 0) Pkts 112 Frames 2 UsedBytes 1486784 audio 19:12:34.330 video 19:03:02.735 Delay 0ms diff -571595ms
Feb 18 08:42:14 rpi4 vdr[22520]: [22534] [softhddevice][AV_Sync] Frame duped (drop 212, dup 0) Pkts 111 Frames 2 UsedBytes 1486592 audio 19:12:34.351 video 19:12:38.175 Delay 0ms diff 3824ms
Feb 18 08:42:14 rpi4 vdr[22520]: [22534] [softhddevice][AV_Sync] Frame duped (drop 212, dup 1) Pkts 111 Frames 2 UsedBytes 1486208 audio 19:12:34.391 video 19:12:38.195 Delay 0ms diff 3804ms
Feb 18 08:42:14 rpi4 vdr[22520]: [22534] [softhddevice][AV_Sync] Frame duped (drop 212, dup 2) Pkts 112 Frames 2 UsedBytes 1486016 audio 19:12:34.430 video 19:12:38.215 Delay 0ms diff 3785ms

...... repating .......

Feb 18 08:42:21 rpi4 vdr[22520]: [22534] [softhddevice][AV_Sync] Frame duped (drop 212, dup 188) Pkts 192 Frames 2 UsedBytes 1364288 audio 19:12:41.871 video 19:12:41.935 Delay 0ms diff 64ms
Feb 18 08:42:22 rpi4 vdr[22520]: [22534] [softhddevice][AV_Sync] Frame duped (drop 212, dup 189) Pkts 192 Frames 2 UsedBytes 1359296 audio 19:12:41.911 video 19:12:41.955 Delay 0ms diff 44ms

-> in sync again
```
The full log is [here.](https://vdr.imkreisrum.de/logs/log-skip)

My guess is, that it's wrong here to calculate the audio pts like (input_pts - buffersize) because input_pts is not continous but does a jump and we can't rely on the calculated audio_pts to sync with the remaining video frames. Because the video frames are evaluated to be too late they are dropped. Once the pts of the video frame has done its jump, we need to duplicate the frames again to be in sync. We need to dup of course nearly as many frames as we dropped before.

This was probably the reason, why diffs > 5000ms were ignored in the sync mechanism before? @fwolter Do you have any idea to fix this?

### PR DESCRIPTION
**Pull request by rellla**
A discontinuity happens when a cutted area should be skipped in a replay.
We now detect at the audio side, if the next pts is more than 5s away from the last one.
In this case the renderer skips sync until this timestamp arrives to be rendered and then
invokes a resync by entering BUFFERING.

Todo: If the pts wraps in a jump, this doesn't work atm. -> done

### CODE REVIEW

**Comment by rellla** [comment]
Not long-time tested, but works with a recording where we the pts wrap within the cutted area and with a "normal" recording.

File: audio.cpp [hunk 1]
```diff
@@ -654,8 +654,17 @@ void cSoftHdAudio::Enqueue(uint16_t *buffer, int count, AVFrame *frame)
 
 	m_fillLevel.ReceivedFrames(snd_pcm_bytes_to_frames(m_pAlsaPCMHandle, bytesWritten));
 
-	if (frame->pts != AV_NOPTS_VALUE)
+	if (frame->pts != AV_NOPTS_VALUE) {
+		// discontinuity check, force a resync if the new pts differs more than AV_SYNC_BORDER to the last
+		if (m_inputPts != AV_NOPTS_VALUE && (std::abs(PtsToMs(m_inputPts) - PtsToMs(frame->pts))) > AV_SYNC_BORDER) {
```
Comment (fwolter) [inline audio.cpp:659]:
```suggestion
		if (m_inputPts != AV_NOPTS_VALUE && std::abs(PtsToMs(m_inputPts) - PtsToMs(frame->pts)) > AV_SYNC_BORDER) {
```

Comment (fwolter) [inline audio.cpp:659]: When having a constant or a variable name containing a value with a specific unit, you could append the unit to the name: AV_SYNC_BORDER_MS

File: videorender.cpp [hunk 2]
```diff
@@ -544,26 +545,38 @@ bool cVideoRender::DisplayFrame()
...
+				if (m_resumeAudioScheduled && audioBehindVideoByMs >= 0 && !skipSync) { // resume audio from pause
 					LOGDEBUG2(L_AV_SYNC, "videorender: resuming audio playback: video %s, audio %s", Timestamp2String(videoPtsMs, 1), Timestamp2String(audioPtsMs, 1));
 					m_pAudio->SetPaused(false);
 					m_resumeAudioScheduled = false;
-				} else if (!m_pAudio->IsPaused() && audioBehindVideoByMs > AV_SYNC_THRESHOLD_AUDIO_BEHIND_VIDEO_MS) { // duplicate frame
+				} else if (!m_pAudio->IsPaused() && !skipSync && audioBehindVideoByMs > AV_SYNC_THRESHOLD_AUDIO_BEHIND_VIDEO_MS) { // duplicate frame
 					LogDroppedDuped(audioPtsMs, videoPtsMs, audioBehindVideoByMs);
-
 					m_framePresentationCounter++; // display the current video frame one period longer
-				} else if (!m_pAudio->IsPaused() && !m_lastFrameWasDropped && audioBehindVideoByMs < -AV_SYNC_THRESHOLD_AUDIO_AHEAD_VIDEO_MS) { // drop frame
```
Comment (fwolter) [inline videorender.cpp:555]: Did you remove m_lastFrameWasDropped  intentionally?

File: videorender.cpp [hunk 3]
```diff
@@ -967,11 +981,9 @@ void cVideoRender::SetVideoClock(int64_t pts)
  */
 int64_t cVideoRender::GetVideoClock(void)
 {
-	int64_t pts;
-	m_videoClockMutex.Lock();
-	pts = m_pts;
-	m_videoClockMutex.Unlock();
-	return pts;
+	std::lock_guard<std::mutex> lock(m_videoClockMutex);
```
Comment (fwolter) [inline videorender.cpp:984]: You could use std:atomic<int64_t>. Then, you can simply use m_pts = n to store the value or `return m_pts` in the getter.

File: videorender.cpp (hunk 2 above)
Comment (rellla) [reply videorender.cpp:555]: Hm, I probably had a restructured if-then-else. I can of course include the !m_lastFrameWasDropped into the upper else if again.

**Comment by rellla** [comment]
Thanks for the review, i was too fast with merging, but will adress your suggestions in a follow-up commit
